// Standalone Gradle build that exists only to compile the Kotlin in
// ../src/main/java, so CI can catch compile errors.
//
// It is deliberately a *separate* project rather than a change to
// ../build.gradle.kts and ../settings.gradle. Those are consumed as a
// subproject of a Tauri app's Gradle build, which supplies the Android and
// Kotlin plugin versions from its own pluginManagement; declaring versions
// there risks a "plugin already on the classpath with a different version"
// conflict in every host app. Nothing here is part of the shipped module.
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id("com.android.library") version "8.7.3"
        id("org.jetbrains.kotlin.android") version "2.0.21"
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "blew-kotlin-ci"

// BlewPlugin.kt needs Tauri's annotations. This directory is generated by
// tauri-plugin's build script, so CI has to build tauri-plugin-blew for
// Android before running this.
include(":tauri-android")
project(":tauri-android").projectDir = file("../.tauri/tauri-api")
